---
name: "pre-release"

on:
  push:
    branches:
      - "release"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - uses: actions/checkout@v2
      - name: "Set up Python 3.9"
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: "Build & test"
        run: |
          bash ./script/install-dependencies.sh
          bash ./script/pre-release.sh
          echo "done!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "last-(auto-release-tag)"
          prerelease: true
          draft: true
          title: "Development Build-`r format(Sys.time(), '%d %B, %Y')`"
          files: |
            *.rar